### ISSUE TITLE
Autoreload does not work

### ISSUE THREAD

**Issue by belafarinrod91** [UIUXEngineering/web-worker-in-ng#1]
Hi, 

many thanks for your solution ! I really appreciate it ! Do you also have issues with auto reloading, when you do changes in the webworker file ? It starts to recompile, but it does not auto reload. If I refresh the page, the changes are not applied. 

Do you any hints for me ?

**Comment by jerryorta-dev** [comment]
I do have the same issue. The web worker is a separate build process from Angular. I don't know if te worker build can be invoked with the Angular build using @angular/cli. At a minimum, you can add the watch config the `webpack.worker.config.js`.

See [https://webpack.js.org/configuration/watch/](https://webpack.js.org/configuration/watch/)

Then you will have to run the worker build in a separate command prompt or Terminal window than the Angular CLI.

**Comment by jerryorta-dev** [comment]
Just pushed a change to `webpack.worker.config.js`. See if this works for you.
