### ISSUE TITLE
aot / prod build breaking

### ISSUE THREAD

**Issue by bautistaaa** [UIUXEngineering/web-worker-in-ng#2]
First off you are saving my life with this workaround. However it seems that when I run "npm run worker" it does in bundle everything as its supposed to but it never ends. I have to kill the task in the console for some reason. This is an issue when trying to run "ng build" since the worker tasks never ends it just hangs. Using your webpack worker config verbatim minus the paths I had to change for where my workers reside.

Thanks!

**Comment by bautistaaa** [comment]
nevermind just realized I had to flip the watch flag off in the webpack config!

**Comment by bautistaaa** [comment]
going to reopen this cause it seems it doesnt work with --prod --aot flags enabled.

```
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\561374\Desktop\workspace\web-worker-in-ng\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

**Comment by dpsthree** [comment]
Mine is building with prod mode with no complications. I updated the dependencies though:
webpack: 3.5.4,
worker-loader: 0.8.1

**Comment by jerryorta-dev** [comment]
Thanks for reporting. The worker task is set to continuously compile. In my workflow, I run the worker task in a separate terminal window than Angular. I commit the compiled bundle as well. This is because the majority of my work is in Angular rather than the Web Worker.

Do you want a different workflow? PR's welcome. 

I will look into the aot as well.

**Comment by bautistaaa** [comment]
Yeah i ended up taking the same approach and just running npm run worker in a separate terminal and removing it from the start/build commands. Seems to be working ok so far. Haven't tried @dpsthree solution yet but will look into that as well.

Thanks!

**Comment by bautistaaa** [comment]
@dpsthree  late on this but I just got around to updating my deps to what you mentioned. webpack 3.5.4 and worker-loader 0.8.1 and still getting the same errors.

only modifications I made to the repo is i changed the build script to use the --prod --aot flags and update the deps to what you recommended

using npm 5.0.3 and node 6.10.1

any ideas?

heres my package.json

{
  "name": "web-worker-in-ng",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "npm run worker && ng serve",
    "build": "npm run worker && ng build --prod --aot",
    "test": "npm run worker && ng test",
    "lint": "ng lint",
    "e2e": "npm run worker && ng e2e",
    "worker": "webpack --config webpack.worker.config.js",
    "serve.build": "lite-server"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "lodash": "^4.17.4",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.4",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/lodash": "^4.14.64",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.3.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0",
    "webpack": "3.5.4",
    "worker-loader": "^0.8.1"
  }
}

**Comment by jerryorta-dev** [comment]
ok, I have to look into this deeper. thank you.

**Comment by bautistaaa** [comment]
HEY I FIXED IT! 

npm i enhanced-resolve@3.3.0 was the trick. 

Got the answer here after fear struck my heart with a 11meg vendor bundle. Down to 3 megs now but its better than 11 :p

https://github.com/angular/angular-cli/issues/7113

**Comment by jerryorta-dev** [comment]
Thanks for your work @bautistaaa

**Comment by bautistaaa** [comment]
I can make a PR if you want.

**Comment by jerryorta-dev** [comment]
That would be great!
